### ISSUE TITLE
[Feature Proposal] Add a 'location' field

### ISSUE THREAD

**Issue by jcletousey** [skinofthesoul/grav-plugin-simple-events#1]
For now I add the location information in the title of the event but it causes me problems to style the templates as it does not have its own field.

Locations of my events are all different so in my case it does not make sense to use the _regions_ field. In my case, it would be better to have a text field.

Do you think it makes sense to add this field ?

By the way, your plugin is great.

**Comment by skinofthesoul** [comment]
Hello there,

thank you for writing, I am glad that it is helpful to you! And I'm *super* sorry that I couldn't reply earlier, my life has been a rollercoaster ride for a while.

I do however have some time now, and your proposal makes sense to me. I'm a bit mindful of feature creep though… I'm pretty sure the Events plugin has a location field, and if you are doing anything more than generate a list of events, you're probably better off using that.

That being said, it's absolutely reasonable to want a list of events with their location specifically styled. I originally wrote this plugin with the specific needs of a client in mind, and their location gets written in the title and linked to a page with some info on that location, so that's sorted for them (if you're curious, [you can check it out here](https://handgestenspiele.de/termine.html), it's in German though).

Anyway, I think I shall add an extra location field, maybe I'll make it optional. Actually I might make the link field optional, I guess not everybody will be using that either… If anybody wants to chime in on ways of keeping the plugin and its usage simple while still providing sensible features, feel free!

**Comment by skinofthesoul** [comment]
Hey there, so I finally managed to add that location field, and also release some non-buggy code! Check out the new release v1.2.1 (which is not correctly numbered, but well, I'm still straightening my life out, that's just how it is right now). I hope this helps you out!
